Entity 연관관계, 멤버변수 수정
DOROEDU/Doro-Server pull request #9
Opened 2023-04-04 14:30 UTC by BangTtagGum

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [x] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
BangTtagGum/jun -> Doro-Server/develop

### 변경 사항
양방향 연관관계 제거, cascade 제거, 멤버변수 Validation 추가

2023-04-05 02:16 UTC, weightsforfun commented
good job

2023-04-05 02:16 UTC, weightsforfun approved these changes
good job

2023-04-05 04:36 UTC, Ju-yeop reviewed
- Chat Entity에서 Message에 대한 OneToMany 빼고 Message Entity애서 ManyToOne 추가해야 되지 않나요?
- LectureDate 임베디드 값 타입에 lectureDates를 리스트로 받으려면 @ElementCollection이나 OneToMany로 테이블 따로 빼줘야 하지 않나요?

2023-04-05 04:42 UTC, Ju-yeop requested changes
- Chat Entity에서 Message에 대한 OneToMany 빼고 Message Entity애서 ManyToOne 추가해야 되지 않나요?
- LectureDate 임베디드 값 타입에 lectureDates를 리스트로 받으려면 @ElementCollection이나 OneToMany로 테이블 따로 빼줘야 하지 않나요?

2023-04-06 04:23 UTC, Ju-yeop approved these changes

2023-04-06 04:24 UTC, merged